feat(frontend): add view task ui
CMSC-129A-Projects/GiTrack pull request #33
Opened 2021-04-21 08:01 UTC by PatTumulak

- Added View Task UI
- Fixed LoginSignup page background
- Made Card component clickable

View Task UI:
![Screen Shot 2021-04-21 at 3 59 49 PM](https://user-images.githubusercontent.com/45306217/115518342-a1606d00-a2ba-11eb-8a20-d7c7e5c4c82e.png)

LoginSignup page:
![Screen Shot 2021-04-21 at 4 00 53 PM](https://user-images.githubusercontent.com/45306217/115518487-cbb22a80-a2ba-11eb-8c1b-343bf4859f55.png)

2021-04-21 08:26 UTC, ohhskar requested changes

2021-04-21 08:26 UTC, ohhskar commented on frontend/package.json
> +    "classnames": "^2.3.1",
Ngano ga add ka ug classnames nga package pero wala gigamit?

2021-04-21 08:29 UTC, justinpo commented on frontend/src/components/Card/card-styles.js
> +  }
ay wait mu gana ra ni pat? ang better diay nga pamaagi kay i replace ang mga `.card___clickable` to `&` ra, so balig ma `&:hover` so on and so forth, my bad

2021-04-21 08:33 UTC, PatTumulak commented on frontend/package.json
> +    "classnames": "^2.3.1",
ahh ako unta siya gamiton but then wa ni work ako gibuhat

2021-04-21 10:10 UTC, ohhskar submitted a review, later dismissed

2021-04-21 10:10 UTC, ohhskar commented
SGTM

2021-04-22 11:23 UTC, justinpo approved these changes

2021-04-22 11:24 UTC, merged