feat(frontend): add Add Repository modals
CMSC-129A-Projects/GiTrack pull request #43
Opened 2021-04-27 16:08 UTC by PatTumulak

added Add Repository modals
![Screen Shot 2021-04-27 at 11 58 18 PM](https://user-images.githubusercontent.com/45306217/116275010-c6bb1280-a7b5-11eb-97a5-f1f9eeb3ecef.png)
![Screen Shot 2021-04-27 at 11 28 55 PM](https://user-images.githubusercontent.com/45306217/116275016-c884d600-a7b5-11eb-9988-d993852c9533.png)

2021-04-27 16:26 UTC, ohhskar requested changes

2021-04-27 16:26 UTC, ohhskar commented on frontend/src/routes/Board/BoardIndex/board-index.jsx
> +import AddTaskModal from 'widgets/AddRepoModal';
AddRepoModal?

2021-04-27 16:26 UTC, ohhskar commented on frontend/src/widgets/AddRepoModal/add-repo-modal-styles.js
> +  margin: 0 0 16px 0;
1rem instead of 16px

2021-04-27 16:26 UTC, ohhskar commented on frontend/src/widgets/SigninGithubModal/signin-github-modal-styles.js
> +  width: 52px;
px -> rem

2021-04-27 16:26 UTC, ohhskar commented on frontend/src/widgets/SigninGithubModal/signin-github-modal-styles.js
> +  width: 120px;
px -> rem

2021-04-27 16:27 UTC, ohhskar approved these changes

2021-04-27 16:27 UTC, ohhskar commented
LGTM

2021-04-28 14:05 UTC, justinpo approved these changes

2021-04-28 14:05 UTC, merged